import "dotenv/config";
import express, { type Request, Response, NextFunction } from "express";
import { registerRoutes } from "./routes";
import { serveStatic } from "./static";
import { createServer } from "http";
import { DB_FILE, DB_PROVIDER } from "./db";
import helmet from "helmet";
import rateLimit, { ipKeyGenerator } from "express-rate-limit";
import { sql } from "drizzle-orm";
import { readCookie, SESSION_COOKIE } from "./routes/auth-cookies";
import crypto from "crypto";
import { dbGet } from "./db-query";
import { getPgPool, closePgPool } from "./pg-pool";
import { scheduleTempCaseAttachmentCleanup } from "./temp-attachment-cleanup";
import { schedulePasswordResetIdCardMaintenance } from "./password-reset-id-card-cleanup";
import { scheduleSiteBackupJobs } from "./backup-scheduler";
import { assertProductionAttachmentSigningConfigured } from "./services/attachment-signing";

const app = express();
const httpServer = createServer(app);
app.set("trust proxy", 1);

declare module "http" {
  interface IncomingMessage {
    rawBody: unknown;
  }
}
declare module "express-serve-static-core" {
  interface Request {
    requestId?: string;
  }
}

app.use(
  express.json({
    limit: "1mb",
    verify: (req, _res, buf) => {
      req.rawBody = buf;
    },
  }),
);

app.use((req, res, next) => {
  const incoming = req.header("x-request-id");
  const requestId =
    typeof incoming === "string" && incoming.trim()
      ? incoming.trim()
      : crypto.randomUUID();
  req.requestId = requestId;
  res.setHeader("x-request-id", requestId);
  next();
});

app.use(express.urlencoded({ extended: false }));

/**
 * CORS allowlist (defence in depth).
 *
 * In the default deployment the built SPA and the API are served from the
 * SAME origin by this Express process, so cross-origin requests never happen
 * and no CORS headers are needed. To support split deployments (SPA on a
 * different domain than the API) without ever using a wildcard, we read an
 * explicit allowlist from `CORS_ALLOWED_ORIGINS` (comma-separated, e.g.
 * "https://app.example.com,https://staging.example.com").
 *
 * Behaviour:
 * - No env set            -> no CORS headers emitted; same-origin only. The
 *                            browser blocks any cross-origin call (safe default).
 * - Origin in allowlist   -> reflect that exact origin (never "*").
 * - Origin NOT allowlisted -> no ACAO header; preflight is rejected with 403.
 *
 * Sessions are carried in an httpOnly cookie (browser) with an Authorization
 * Bearer fallback (tests / non-browser callers). For the default same-origin
 * deployment CORS never fires. For an allowlisted cross-origin SPA we reflect
 * the exact origin and allow credentials so the session cookie can be sent
 * (the client must then use `credentials: "include"`); the CSRF header is
 * whitelisted so the double-submit token can cross.
 */
const CORS_ALLOWED_ORIGINS = (process.env.CORS_ALLOWED_ORIGINS ?? "")
  .split(",")
  .map((origin) => origin.trim())
  .filter(Boolean);

app.use((req, res, next) => {
  const origin = req.headers.origin;
  const isAllowed = typeof origin === "string" && CORS_ALLOWED_ORIGINS.includes(origin);

  if (isAllowed) {
    res.setHeader("Access-Control-Allow-Origin", origin as string);
    res.setHeader("Vary", "Origin");
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Access-Control-Allow-Methods", "GET,POST,PATCH,PUT,DELETE,OPTIONS");
    res.setHeader(
      "Access-Control-Allow-Headers",
      "Authorization,Content-Type,X-Request-Id,X-CSRF-Token",
    );
    res.setHeader("Access-Control-Max-Age", "600");
  }

  if (req.method === "OPTIONS") {
    // Preflight: succeed only for allowlisted origins. A cross-origin preflight
    // from a non-allowlisted origin is rejected instead of silently passing.
    if (isAllowed) return res.sendStatus(204);
    if (typeof origin === "string") return res.sendStatus(403);
    // Same-origin (no Origin header) preflight: let it fall through.
  }

  next();
});

/**
 * Helmet hardening.
 *
 * - Production: explicit CSP (no inline scripts; styles/images/fonts limited
 *   to same-origin + data: where the UI needs it). The previous default
 *   policy was generated by Helmet defaults, which is fine, but we make
 *   it explicit so future audits can reason about it.
 * - Dev: CSP disabled so Vite's HMR/eval pipeline keeps working.
 * - `crossOriginResourcePolicy: "same-site"` so other origins can't embed
 *   our signed-attachment URLs as <img>/<script> via cross-site requests.
 */
if (process.env.NODE_ENV === "production") {
  app.use(
    helmet({
      crossOriginResourcePolicy: { policy: "same-site" },
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          defaultSrc: ["'self'"],
          baseUri: ["'self'"],
          objectSrc: ["'none'"],
          frameAncestors: ["'self'"],
          scriptSrc: ["'self'"],
          styleSrc: ["'self'", "'unsafe-inline'"],
          imgSrc: ["'self'", "data:", "blob:"],
          fontSrc: ["'self'", "data:"],
          connectSrc: ["'self'"],
          formAction: ["'self'"],
          upgradeInsecureRequests: null,
        },
      },
    }),
  );
} else {
  app.use(
    helmet({
      contentSecurityPolicy: false,
      crossOriginResourcePolicy: { policy: "same-site" },
    }),
  );
}
/**
 * Stricter limiter on credential-touching endpoints. Mounted BEFORE the
 * blanket /api limiter so the stricter window wins. The audit flagged the
 * previous single 1000 req / 15 min bucket as too permissive against
 * password-guessing — a single attacker IP could burn ~66/minute against
 * /api/auth/login without tripping anything.
 *
 * Bucketing is per-IP. We use `skipSuccessfulRequests: true` on login/reset
 * so a legitimate user typing the wrong password once isn't locked out
 * after the first success.
 */
const authLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 20,
  standardHeaders: true,
  legacyHeaders: false,
  skipSuccessfulRequests: true,
  message: {
    message:
      "Too many credential attempts. Please wait 15 minutes and try again.",
  },
});

app.use(
  [
    "/api/auth/login",
    "/api/auth/login/2fa",
    "/api/auth/signup",
    "/api/auth/password-reset-requests",
    "/api/auth/totp/verify",
  ],
  authLimiter,
);

/**
 * Per-key budget for the general API limiter.
 *
 * Keyed per *session* (the `vth_session` cookie) rather than per IP, because an
 * entire campus/hospital is often behind a single NAT public IP. With per-IP
 * keying everyone there shared one bucket and could trip the limit during busy
 * periods even though no single person was abusing anything. Keying per session
 * gives each logged-in device its own budget.
 *
 * Requests with no session cookie (logged-out, static-asset fetches, health
 * checks, and non-browser Bearer callers such as tests) fall back to the
 * IP-based key via `ipKeyGenerator`, which also normalises IPv6 correctly. The
 * fallback is mandatory: without it, every cookieless request would collapse
 * into a single shared bucket and throttle each other.
 */
app.use(
  "/api",
  rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 2000,
    standardHeaders: true,
    legacyHeaders: false,
    keyGenerator: (req) => {
      const token = readCookie(req, SESSION_COOKIE);
      if (token) return `sess:${token}`;
      return ipKeyGenerator(req.ip ?? "");
    },
    message: {
      message: "Too many requests. Please retry later.",
    },
  }),
);

function log(message: string, source = "express") {
  const formattedTime = new Date().toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });

  console.log(`${formattedTime} [${source}] ${message}`);
}

function logJson(
  entry: Record<string, unknown>,
  source = "express",
): void {
  const payload = { source, timestamp: new Date().toISOString(), ...entry };
  console.log(JSON.stringify(payload));
}

app.use((req, res, next) => {
  const start = Date.now();
  const path = req.path;
  let capturedJsonResponse: unknown = undefined;

  const originalResJson = res.json;
  res.json = function (bodyJson, ...args) {
    capturedJsonResponse = bodyJson;
    return originalResJson.apply(res, [bodyJson, ...args]);
  };

  res.on("finish", () => {
    const duration = Date.now() - start;
    if (path.startsWith("/api")) {
      // Response body logging is intentionally restricted to non-production
      // because API payloads regularly contain PHI (patient info, case
      // attachments, user emails). Set LOG_RESPONSE_BODIES=true *and*
      // NODE_ENV!=production to enable.
      const logBody =
        process.env.LOG_RESPONSE_BODIES === "true" &&
        process.env.NODE_ENV !== "production";
      logJson({
        type: "api_request",
        requestId: req.requestId,
        method: req.method,
        path,
        statusCode: res.statusCode,
        durationMs: duration,
        responseBody: logBody && capturedJsonResponse ? capturedJsonResponse : undefined,
      });
    }
  });

  next();
});

app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "vet-ast-app",
    uptimeSeconds: Math.floor(process.uptime()),
    timestamp: new Date().toISOString(),
  });
});

app.get("/api/ready", async (_req, res) => {
  try {
    if (DB_PROVIDER === "postgres") {
      await getPgPool().query("SELECT 1 as ready");
    } else {
      await dbGet(sql`SELECT 1 as ready`);
    }
    res.json({
      status: "ready",
      database: DB_PROVIDER === "postgres" ? "postgres" : DB_FILE,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    res.status(503).json({
      status: "not_ready",
      message: "Database unavailable",
      error: error instanceof Error ? error.message : "Unknown error",
    });
  }
});

(async () => {
  process.on("unhandledRejection", (reason) => {
    const message = reason instanceof Error ? reason.message : String(reason);
    const stack = reason instanceof Error ? reason.stack : undefined;
    logJson({
      type: "unhandled_rejection",
      message,
      stack,
      hint: "A Promise was rejected without .catch(); the process may exit depending on Node settings. Check server logs above.",
    });
  });

  if (process.env.NODE_ENV === "production" && process.env.ALLOW_DEFAULT_ADMIN === "true") {
    logJson({
      type: "startup_warning",
      message:
        "ALLOW_DEFAULT_ADMIN=true in production. This should be disabled after initial bootstrap.",
    });
  }

  if (process.env.NODE_ENV === "production" && process.env.LOG_RESPONSE_BODIES === "true") {
    logJson({
      type: "startup_warning",
      message:
        "LOG_RESPONSE_BODIES=true is ignored in production (PHI leak risk). Use NODE_ENV!=production to enable.",
    });
  }

  assertProductionAttachmentSigningConfigured();

  await registerRoutes(httpServer, app);

  app.use((err: any, _req: Request, res: Response, next: NextFunction) => {
    const status = err.status || err.statusCode || 500;
    const message = err.message || "Internal Server Error";

    logJson({
      type: "api_error",
      requestId: _req.requestId,
      status,
      message,
      stack: err instanceof Error ? err.stack : undefined,
      path: _req.path,
      method: _req.method,
    });

    if (res.headersSent) {
      return next(err);
    }

    // In production, never surface raw 5xx error messages to the client — they
    // can leak internal implementation detail (stack fragments, query text,
    // file paths). The full message + stack is logged above with the requestId
    // so support can correlate. 4xx messages are intentional/user-facing and
    // are passed through unchanged.
    const clientMessage =
      status >= 500 && process.env.NODE_ENV === "production"
        ? "Internal Server Error"
        : message;

    return res.status(status).json({ message: clientMessage, requestId: _req.requestId });
  });

  // Never allow SPA/Vite fallback to answer unknown API routes with HTML.
  app.use((req: Request, res: Response, next: NextFunction) => {
    const p = req.path || "";
    if (!p.startsWith("/api")) return next();
    if (res.headersSent) return next();
    return res.status(404).json({
      message: `API route not found: ${req.method} ${p}`,
      requestId: req.requestId,
    });
  });

  // importantly only setup vite in development and after
  // setting up all the other routes so the catch-all route
  // doesn't interfere with the other routes
  if (process.env.NODE_ENV === "production") {
    serveStatic(app);
  } else {
    const { setupVite } = await import("./vite");
    await setupVite(httpServer, app);
  }

  // ALWAYS serve the app on the port specified in the environment variable PORT
  // Other ports are firewalled. Default to 5000 if not specified.
  // this serves both the API and the client.
  // It is the only port that is not firewalled.
  const port = parseInt(process.env.PORT || "5000", 10);
  httpServer.requestTimeout = 120_000;
  httpServer.headersTimeout = 65_000;
  httpServer.keepAliveTimeout = 60_000;

  const server = httpServer.listen(
    {
      port,
      host: "0.0.0.0",
    },
    () => {
      log(`serving on port ${port}`);
      log(`db provider: ${DB_PROVIDER}`);
      log(`using database: ${DB_FILE}`);
      scheduleTempCaseAttachmentCleanup();
      schedulePasswordResetIdCardMaintenance();
      scheduleSiteBackupJobs();
    },
  );

  const shutdown = (signal: string) => {
    logJson({ type: "shutdown_signal", signal });
    server.close(async (err?: Error) => {
      if (err) {
        logJson({
          type: "shutdown_error",
          signal,
          message: err.message,
        });
      }
      try {
        await closePgPool();
      } catch (poolErr) {
        logJson({
          type: "shutdown_pg_pool_error",
          signal,
          message:
            poolErr instanceof Error ? poolErr.message : String(poolErr),
        });
      }
      if (err) {
        process.exit(1);
      }
      logJson({ type: "shutdown_complete", signal });
      process.exit(0);
    });
    setTimeout(() => {
      logJson({ type: "shutdown_timeout", signal });
      process.exit(1);
    }, 10_000).unref();
  };

  process.on("SIGTERM", () => shutdown("SIGTERM"));
  process.on("SIGINT", () => shutdown("SIGINT"));

  process.on("uncaughtException", (error) => {
    logJson({
      type: "uncaught_exception",
      message: error.message,
      stack: error.stack,
    });
    shutdown("uncaughtException");
  });
})();
